# Generated by Django 3.2.12 on 2022-11-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='title',
            new_name='tittle',
        ),
    ]
