# Generated by Django 3.2.12 on 2022-11-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_title_todolist_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='title',
            new_name='tasktitle',
        ),
    ]
