# Generated by Django 3.2.12 on 2022-11-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_title_todoitem_tasktitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='tittle',
            new_name='title',
        ),
    ]
